server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: url-shortner-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG